version: '3'

services:
  fastapi:
    volumes: 
      - ./fastapi:/usr/src/app
    build: 
      context: ./
      dockerfile: Dockerfile_fastapi
    ports:
      - "8000:8000"
  streamlit:
    volumes: 
      - ./streamlit:/usr/src/app
    build: 
      context: ./
      dockerfile: Dockerfile_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi